[book]
authors = ["Nicolas Di Prima"]
language = "en"
multilingual = false
src = "src"
title = "ASMTP"
[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[output]
[output.html]
mathjax-support = true
additional-js =["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]  # enable the "mdbook-linkcheck" rendere